### PR TITLE
Update Cheese runtime to 46

### PR DESCRIPTION
**Pull request by ghost**
- Update Cheese runtime to 46 since runtime version 44 has reached end-of-life.
- Update Cheese version to 44.1.
- Fix appdata papercuts.
- Update shared-modules.

### CODE REVIEW

**Comment by ghost** [comment]
@A6GibKm I've updated Cheese runtime to 46 since runtime version 44 has reached end-of-life.

I'm not sure about the following commit: https://github.com/flathub/org.gnome.Cheese/pull/38/commits/af602ef9ff304d3fc1330abe9ed27a1932b96728

Could you review changes.

Thanks.

**Comment by A6GibKm** [comment]
> @A6GibKm I've updated Cheese runtime to 46 since runtime version 44 has reached end-of-life.
> 
> I'm not sure about the following commit: [af602ef](https://github.com/flathub/org.gnome.Cheese/commit/af602ef9ff304d3fc1330abe9ed27a1932b96728)
> 
> Could you review changes.
> 
> Thanks.

Hello and thanks!

I am trying to limit my maintenance to apps I maintain and core GNOME modules and this is not one. Nevertheless, please drop or split into a different PR the commit https://github.com/flathub/org.gnome.Cheese/commit/af602ef9ff304d3fc1330abe9ed27a1932b96728 and I can test this and merge the other 4 commits later today.

**Comment by A6GibKm** [comment]
Thanks!

**Comment by ghost** [comment]
Sent to upstream: https://gitlab.gnome.org/GNOME/cheese/-/merge_requests/72

**Pull request merged**
